import {Accounts, Collections, Explore, Settings, Swap, Wallet} from "../views/index.slint";
import {ViewManager, View} from "../managers/view-manager.slint";

export component Main {
    if ViewManager.active_view == View.accounts : Accounts {}
    if ViewManager.active_view == View.collections : Collections {}
    if ViewManager.active_view == View.explore : Explore {}
    if ViewManager.active_view == View.settings : Settings {}
    if ViewManager.active_view == View.swap : Swap {}
    if ViewManager.active_view == View.wallet : Wallet {}
}