import {Palette} from "std-widgets.slint";
import {AppView} from "components/AppView.slint";
import {SolScanBtn} from "components/SideNav/Account.slint";
import {Account, AccountManager} from "utils/account-manager.slint";
import {AppManager} from "utils/app-manager.slint";

export component App inherits Window {
    background: Palette.alternate-background.darker(0.25);
    preferred-width: 900px;
    preferred-height: 600px;
    no-frame: false;
    always-on-top: false;
    title: "Solana Desktop Wallet";

    AppView {}
}

export {Account, AccountManager, SolScanBtn}