import {Palette} from "std-widgets.slint";
import {AppView} from "components/AppView.slint";
import {Wallet, WalletManager} from "utils/account-manager.slint";

export component App inherits Window {
    background: Palette.alternate-background.darker(0.25);
    preferred-width: 900px;
    preferred-height: 600px;
    no-frame: false;
    always-on-top: false;
    title: "Solana Desktop Wallet";

    AppView {}
}

export {Wallet, WalletManager}