import {Palette} from "std-widgets.slint";

export global Theme  {
    private property <color> off_white: rgba(255,255,255,0.85);
    out property <color> background: rgb(18,18,18);
    out property <color> on_background: off_white;
    out property <color> surface: rgb(33,33,33);
    out property <color> on_surface: off_white;
    out property <color> primary: rgb(41,121,255);
    out property <color> on_primary: off_white;
    out property <color> accent: #9C27B0;
    out property <color> secondary: Palette.foreground.with-alpha(0.9);
}