import {HorizontalBox, VerticalBox, Palette} from "std-widgets.slint";

component AddAccountButton inherits Rectangle {
    in property <image> icon;
    in property <physical-length> iccn_size: 15px;
    in property <physical-length> button_height: 32px;
    in property <physical-length> button_width: 120px;
    in property <physical-length> button_radius: 6px;

    callback clicked();

    height: button_height;
    width: button_width;
    border-radius: button_radius;
    background: Palette.foreground.with-alpha(0.90);


    HorizontalBox {
        alignment: center;
//        Image { visible: false; source: icon; width: iccn_size; }
        Text {text: "Add Account"; font-size: 12px; font-weight: 600; color: Palette.background;}
    }

    states [
        pressed when touch.pressed: {
            root.background: Palette.foreground.with-alpha(0.70);
        }
        hover when touch.has-hover: {
            root.background: Palette.foreground.with-alpha(0.85);
        }
    ]

    touch := TouchArea {
        clicked => { root.clicked(); }
    }
}

export component AccountsToolbar inherits Rectangle {
    height: 80px;
    HorizontalBox {
        alignment: space-between;
        VerticalLayout {
            alignment: center;
            AddAccountButton {}
        }
    }
}