import {VerticalBox, Palette} from "std-widgets.slint";

export component AccountsListHeader {
    VerticalBox {
        Rectangle {
            height: 30px;
            HorizontalLayout {
                alignment: space-between;
                VerticalLayout {
                    alignment: center;
                    width: 300px;
                    Text {
                        font-weight: 600;
                        font-size: 21px;
                        text: "Name";
                        color: Palette.foreground.with-alpha(0.85);
                        horizontal-alignment: left;
                    }
                }

                VerticalLayout {
                    alignment: center;
                    width: 300px;
                    Text {
                        font-weight: 600;
                        font-size: 21px;
                        text: "Pubkey";
                        color: Palette.foreground.with-alpha(0.85);
                        horizontal-alignment: left;
                    }
                }

                VerticalLayout {
                    alignment: center;
                    width: 200px;
                    Text {
                        font-weight: 600;
                        font-size: 21px;
                        text: "Balance";
                        color: Palette.foreground.with-alpha(0.85);
                        horizontal-alignment: left;
                    }
                }
            }
        }
    }
}