import {ListView} from "std-widgets.slint";
import {AccountManager} from "../../../managers/account-manager.slint";
import {AccountListItem} from "AccountListItem.slint";
import {Theme} from "../../../theme.slint";

export component AccountsList {
    private property <int> selected_account_id: AccountManager.selected_account.id;
    pure function set_item_bg_color(id: int, index: int) -> color {
        if (id == selected_account_id) {
            return Theme.alternate_background;
        }
        return Math.mod(index, 2) == 0 ?  Theme.surface.darker(0.25) : Theme.background;
    }
    ListView {
        for account[index] in AccountManager.accounts : AccountListItem {
            account: account;
            background_color: Math.mod(index, 2) == 0 ?  Theme.surface.darker(0.25) : Theme.background;
        }
    }
}