import {VerticalBox, Button, HorizontalBox} from "std-widgets.slint";
import {AccountManager} from "../../managers/account-manager.slint";
import {View, ViewManager} from "../../managers/view-manager.slint";
import {AppButton, AppButtonType} from "../AppButton.slint";

export component SideNavAccount {
    height: 120px;

    VerticalBox {
        spacing: 3px;
        height: 70px;

        Text {
            font-size: 15px;
            font-weight: 700;
            text: AccountManager.selected_account.name;
            overflow: TextOverflow.elide;
        }

        VerticalLayout {
            alignment: center;
            height: 30px;
            HorizontalLayout {
                VerticalLayout {
                    alignment: center;
                    Text {
                        text: AccountManager.selected_account.pubkey_display;
                        font-size: 15px;
                        font-weight: 500;
                    }
                }

                AppButton {
                    label: "View On Solscan";
                    icon: @image-url("../../assets/icons/open-icon.svg");
                    clicked => {
                        AccountManager.view_account(AccountManager.selected_account.pubkey)
                    }
                }
            }
        }
    }
}

