import {Palette, VerticalBox, Button} from "std-widgets.slint";
import {Account, AccountManager} from "../../utils/account-manager.slint";

export component SideNavAccount {
    height: 120px;

    VerticalBox {
        spacing: 3px;
        height: 100px;
        Text {
            font-size: 15px;
            font-weight: 700;
            text: AccountManager.selected_account.name;
        }
        Text {
            text: AccountManager.selected_account.pubkey_display;
            font-weight: 500;
        }
        VerticalLayout {
            padding-top: 9px;
            Button { text: "View Accounts"; }
        }
    }
}