import {VerticalBox, Button, HorizontalBox, Palette} from "std-widgets.slint";
import {AccountManager} from "../../managers/account-manager.slint";
import {View, ViewManager} from "../../managers/view-manager.slint";
import {AppButton} from "../AppButton.slint";

export component SolScanBtn inherits Rectangle {
    background: Palette.alternate_background;
    border-radius: 6px;
    property <image> icon: @image-url("../../assets/icons/open-icon.svg");
    property <string> label: "view on Solscan";

    HorizontalBox {
        alignment: center;
        Image {source: icon; width: 12px;}
        Text {text: label; font-size: 12px;}
    }
    states [
        pressed when touch.pressed: {
            root.opacity: 0.5;
            root.background: Palette.alternate-background;
        }
        hover when touch.has-hover: {
            root.opacity: 0.7;
            root.background: Palette.alternate-background;
        }
    ]
    touch := TouchArea {
        clicked => {
            AccountManager.view_account(AccountManager.selected_account.pubkey)
        }
    }
}

export component SideNavAccount {
    height: 120px;

    VerticalBox {
        spacing: 3px;
        height: 100px;

        Text {
            font-size: 15px;
            font-weight: 700;
            text: AccountManager.selected_account.name;
            overflow: TextOverflow.elide;
        }
        
        VerticalLayout {
            alignment: center;
            height: 30px;
            HorizontalLayout {
                VerticalLayout {
                    alignment: center;
                    Text {
                        text: AccountManager.selected_account.pubkey_display;
                        font-size: 15px;
                        font-weight: 500;
                    }
                }
                AppButton {
                    label: "View On Solscan";
                    icon: @image-url("../../assets/icons/open-icon.svg");
                    clicked => {

                    }
                }
            }
        }

        VerticalLayout {
            padding-top: 9px;
            Button {
                text: "View Accounts";
                clicked => {
                    ViewManager.activeView = View.accounts
                }
            }
        }
    }
}