import {HorizontalBox} from "std-widgets.slint";
import {SideNavAccount, SideNavList, SideNavSolValue} from "components.slint";
import {Theme} from "../../theme.slint";

export component SideNav inherits Rectangle {
    background: Theme.background;
    width: 300px;

    HorizontalBox {
        VerticalLayout {
            spacing: 9px;
            SideNavSolValue { }

            SideNavAccount { }

            SideNavList { }
        }
    }
}

