import {Palette, VerticalBox } from "std-widgets.slint";

export component SideNavList inherits VerticalBox {
    VerticalLayout {
        Text {
            font-size: 12px;
            text: "Wallet";
        }
        Text {
            font-size: 12px;
            text: "Collections";
        }
        Text {
            font-size: 12px;
            text: "Swap";
        }
        Text {
            font-size: 12px;
            text: "Activites";
        }
        Text {
            font-size: 12px;
            text: "Settings";
        }
    }
}