import {HorizontalBox}  from "std-widgets.slint";
import {ViewManager, View} from "../../managers/view-manager.slint";
import {Theme} from "../../theme.slint";

export struct ListItem {
    view: View,
    icon: image,
    label: string
}

export component SideNavListItem inherits Rectangle {
    background: root.is_view ? Theme.surface : Theme.background;
    height: 36px;
    border-radius: 6px;
    in-out property<View> view;
    in-out property<string> label;
    in-out property<image> icon;

    property <bool> is_view: ViewManager.activeView == root.view;

    HorizontalBox {
        Image{
            source: icon;
            width: 21px;
            colorize: root.is_view ? Theme.primary.brighter(0.50) : Theme.on_background;
        }

        Text {
            vertical-alignment: center;
            font-size: 15px;
            font-weight: 600;
            text: label;
            color: Theme.on_background;
        }
    }
    states [
        pressed when touch.pressed: {
            root.background: Theme.surface.with-alpha(0.65);
        }
        hover when touch.has-hover: {
            root.background: Theme.surface.with-alpha(0.8);
        }
    ]
    touch := TouchArea {
        clicked => {
            ViewManager.activeView = view;
        }
    }
}