import {Palette, HorizontalBox}  from "std-widgets.slint";
import {ViewManager, View} from "../../managers/view-manager.slint";
import {CustomTheme} from "../../theme.slint";

export struct ListItem {
    view: View,
    icon: image,
    label: string
}

export component SideNavListItem inherits Rectangle {
    background: root.is_view ? Palette.alternate-background : Palette.background;
    height: 36px;
    border-radius: 6px;
    in-out property<View> view;
    in-out property<string> label;
    in-out property<image> icon;

    property <bool> is_view: ViewManager.activeView == root.view;

    HorizontalBox {
        Image{
            source: icon;
            width: 21px;
            colorize: root.is_view ? CustomTheme.primary.brighter(0.50) : Palette.foreground;
        }

        Text {
            vertical-alignment: center;
            font-size: 15px;
            font-weight: 600;
            text: label;
            color: Palette.foreground.with-alpha(0.85);
        }
    }
    states [
        pressed when touch.pressed: {
            root.opacity: 0.5;
            root.background: Palette.alternate-background;
        }
        hover when touch.has-hover: {
            root.opacity: 0.7;
            root.background: Palette.alternate-background;
        }
    ]
    touch := TouchArea {
        clicked => {
            ViewManager.activeView = view;
        }
    }
}