import {HorizontalBox, VerticalBox, StandardTableView, Palette, ListView} from "std-widgets.slint";
import {AccountManager} from "../utils/account-manager.slint";

component AccountsListHeader {
    Rectangle {
        height: 48px;

        HorizontalLayout {
            alignment: space-between;
            VerticalLayout {
                alignment: center;
                width: 300px;
                Text {
                    font-weight: 600;
                    font-size: 15px;
                    text: "Name";
                    color: Palette.foreground.with-alpha(0.85);
                    horizontal-alignment: left;
                }
            }

            VerticalLayout {
                alignment: center;
                width: 500px;
                Text {
                    font-weight: 600;
                    font-size: 15px;
                    text: "Pubkey";
                    color: Palette.foreground.with-alpha(0.85);
                    horizontal-alignment: left;
                }
            }

            VerticalLayout {
                alignment: center;
                width: 100px;
                Text {
                    font-weight: 600;
                    font-size: 15px;
                    text: "Balance";
                    color: Palette.foreground.with-alpha(0.85);
                    horizontal-alignment: left;
                }
            }
        }
    }
}

component AccountsList {
    ListView {
        for account in AccountManager.accounts : Rectangle {
            height: 48px;
            HorizontalLayout {
                alignment: space-between;
                VerticalLayout {
                    alignment: center;
                    width: 300px;
                    Text {
                        font-size: 15px;
                        text: account.name;
                        color: Palette.foreground.with-alpha(0.85);
                        horizontal-alignment: left;
                    }
                }

                VerticalLayout {
                    alignment: center;
                    width: 500px;
                    Text {
                        font-size: 15px;
                        text: account.pubkey;
                        color: Palette.foreground.with-alpha(0.85);
                        horizontal-alignment: left;
                    }
                }

                VerticalLayout {
                    alignment: center;
                    width: 100px;
                    Text {
                        font-size: 15px;
                        text: "15.56";
                        color: Palette.foreground.with-alpha(0.85);
                        horizontal-alignment: left;
                    }
                }
            }
        }
    }
}

component AccountListItem {
    
}

export component Accounts inherits HorizontalLayout {
    VerticalBox {
        padding: 30px;
        Rectangle {
            height: 60px;
            VerticalLayout {
                Text {
                    text: "Accounts";
                    font-size: 30px;
                    font-weight: 800;
                    color: Palette.foreground.with-alpha(0.85);
                    horizontal-alignment: left;
                }
            }
        }

        Rectangle {
            background: Palette.alternate-background;
            border-radius: 9px;
            HorizontalBox {
                VerticalBox {
                    AccountsListHeader {}
                    AccountsList {}
                }
            }
        }
    }
}