import {HorizontalBox, VerticalBox, StandardTableView, Palette, ListView} from "std-widgets.slint";
import {AccountManager} from "../utils/account-manager.slint";

component AccountsListHeader {
    Rectangle {
        height: 48px;

        HorizontalLayout {
            alignment: space-between;
            VerticalLayout {
                alignment: center;
                width: 300px;
                Text {
                    font-weight: 600;
                    font-size: 15px;
                    text: "Name";
                    color: Palette.foreground.with-alpha(0.85);
                    horizontal-alignment: left;
                }
            }

            VerticalLayout {
                alignment: center;
                width: 500px;
                Text {
                    font-weight: 600;
                    font-size: 15px;
                    text: "Pubkey";
                    color: Palette.foreground.with-alpha(0.85);
                    horizontal-alignment: left;
                }
            }

            VerticalLayout {
                alignment: center;
                width: 200px;
                Text {
                    font-weight: 600;
                    font-size: 15px;
                    text: "Balance";
                    color: Palette.foreground.with-alpha(0.85);
                    horizontal-alignment: left;
                }
            }
        }
    }
}

component AccountListItem inherits Rectangle {
    in property <string> name;
    in property <string> pubkey;
    in property <string> balance;
    VerticalLayout {
        alignment: center;
        Rectangle {
                height: 48px;
                border-radius: 9px;
                HorizontalLayout {
                    alignment: space-between;
                    VerticalLayout {
                        alignment: center;
                        width: 300px;
                        Text {
                            font-size: 15px;
                            text: name;
                            color: Palette.foreground.with-alpha(0.85);
                            horizontal-alignment: left;
                        }
                    }

                    VerticalLayout {
                        alignment: center;
                        width: 500px;
                        Text {
                            font-size: 15px;
                            text: pubkey;
                            color: Palette.foreground.with-alpha(0.85);
                            horizontal-alignment: left;
                        }
                    }

                    VerticalLayout {
                        alignment: center;
                        width: 200px;
                        Text {
                            font-size: 15px;
                            text: balance;
                            color: Palette.foreground.with-alpha(0.85);
                            horizontal-alignment: left;
                        }
                    }
                }
            }
    }

    states [
        pressed when touch.pressed: {
            root.opacity: 0.5;
            root.background: Palette.alternate-background;
        }
        hover when touch.has-hover: {
            root.opacity: 0.7;
            root.background: Palette.alternate-background;
        }
    ]

    touch := TouchArea {
        clicked => {
            debug("View Account");
        }
    }
}

component AccountsList {
    ListView {
        for account in AccountManager.accounts : AccountListItem {
            name: account.name;
            pubkey: account.pubkey;
            balance: "11.11 SOL";
        }
    }
}

export component Accounts inherits HorizontalLayout {
    VerticalBox {
        padding: 30px;
        Rectangle {
            height: 60px;
            VerticalLayout {
                Text {
                    text: "Accounts";
                    font-size: 30px;
                    font-weight: 800;
                    color: Palette.foreground.with-alpha(0.85);
                    horizontal-alignment: left;
                }
            }
        }

        Rectangle {
            background: Palette.alternate-background;
            border-radius: 9px;
            HorizontalBox {
                VerticalBox {
                    AccountsListHeader {}
                    AccountsList {}
                }
            }
        }
    }
}