import {HorizontalBox, VerticalBox, Palette} from "std-widgets.slint";
import {AccountsList, AccountListItem, AccountsListHeader} from "components/index.slint";

export component Accounts inherits HorizontalLayout {
    padding: 18px;
    VerticalBox {
        Rectangle {
            height: 60px;
            VerticalBox {
                Text {
                    text: "Accounts";
                    font-size: 30px;
                    font-weight: 800;
                    color: Palette.foreground.with-alpha(0.85);
                    horizontal-alignment: left;
                }
            }
        }

        Rectangle {
            HorizontalLayout {
                VerticalLayout {
                    AccountsListHeader {}
                    AccountsList {}
                }
            }
        }
    }
}